 version: '2'

services:
  fpm:
    user: 1000:1000
    image: thijs/php:alpine-php-7.4
    volumes:
      - './:/app'
      - ~/.composer:/.composer
    working_dir: '/app'
    environment:
      COMPOSER_HOME: '/.composer'
